config/routes.rb
Rails.application.routes.draw do
  resources :arts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "arts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art.rb
class Art < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  before_action :set_art, only: [:show, :edit, :update, :destroy]

  # GET /arts
  # GET /arts.json
  def index
    @arts = Art.all
  end

  # GET /arts/1
  # GET /arts/1.json
  def show
  end

  # GET /arts/new
  def new
    @art = Art.new
  end

  # GET /arts/1/edit
  def edit
  end

  # POST /arts
  # POST /arts.json
  def create
    @art = Art.new(art_params)

    respond_to do |format|
      if @art.save
        format.html { redirect_to @art, notice: 'Art was successfully created.' }
        format.json { render :show, status: :created, location: @art }
      else
        format.html { render :new }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arts/1
  # PATCH/PUT /arts/1.json
  def update
    respond_to do |format|
      if @art.update(art_params)
        format.html { redirect_to @art, notice: 'Art was successfully updated.' }
        format.json { render :show, status: :ok, location: @art }
      else
        format.html { render :edit }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arts/1
  # DELETE /arts/1.json
  def destroy
    @art.destroy
    respond_to do |format|
      format.html { redirect_to arts_url, notice: 'Art was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_art
      @art = Art.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def art_params
      params.require(:art).permit(:Title, :Author, :Date, :Picture, :Description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/views/arts/_form.html.erb
<%= form_with(model: art, local: true) do |form| %>
  <% if art.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(art.errors.count, "error") %> prohibited this art from being saved:</h2>

      <ul>
      <% art.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Title %>
    <%= form.text_field :Title %>
  </div>

  <div class="field">
    <%= form.label :Author %>
    <%= form.text_field :Author %>
  </div>

  <div class="field">
    <%= form.label :Date %>
    <%= form.text_field :Date %>
  </div>

  <div class="field">
    <%= form.label :Picture %>
    <%= form.text_field :Picture %>
  </div>

  <div class="field">
    <%= form.label :Description %>
    <%= form.text_area :Description %>
  </div>

  <div class="actions" style="margin-bottom: 10px;">
    <%= form.submit %>
  </div>
<% end %>

app/views/arts/edit.html.erb
<div class="container">
  <p class="mesoeuvrestext">Éditer Œuvre</p>
  <div class="jumbotron">
  	<%= render 'form', art: @art %>
    <%= link_to 'Montrer', @art, class: 'btn btn-primary' %> |
	<%= link_to 'Retour', arts_path, class: 'btn btn-primary' %>
  </div>

</div>

app/views/arts/index.html.erb
  <p id="notice"><%= notice %></p>
  

  <p class="mesoeuvrestext">Les Œuvres</p>
  <div class="row justify-content-center space-evenly" class="mesvignettes">
    <% @arts.each do |art| %>
        <div class="card">
          <div class="divimagevignette" style="background-image: url(<%= art.Picture %>);">
            
          </div>
          <!--<img src="<%= art.Picture %>" class="img-fluid" class="img"/>-->
          <div class="card-body">
            <h5 class="card-title"><%= art.Title %></h5>
            <!--<p class="card-text"><%= art.Description %></p>-->
            <div class="mesboutonvignette">
              <%= link_to 'Montrer', art, class: 'btn btn-primary' %>
              <%= link_to 'Editer', edit_art_path(art), class: 'btn btn-primary' %>
            </div>
          </div>
        </div>

    <% end %>
  </div>

<!--background-image: linear-gradient(to right, red , yellow);-->

app/views/arts/new.html.erb
<div class="container">

  <p class="mesoeuvrestext">Nouvelle Œuvre</p>

  <div class="jumbotron">
  	<%= render 'form', art: @art %>
    <%= link_to 'Retour', arts_path, class: 'btn btn-primary'%>
  </div>

</div>

app/views/arts/show.html.erb
<div class="container">

  <p class="mesoeuvrestext">Détails de l'Œuvres</p>

  <div class="jumbotron">
    <h1 class="display-4"><%= @art.Title %></h1>
    <h2><%= @art.Author %> - <%= @art.Date %></h2>
    <img src="<%= @art.Picture %>" class="img-fluid"/>
    <p class="lead" style="margin-top: 10px;"><%= @art.Description %></p>
    <hr class="my-4">
    <%= link_to 'Editer', edit_art_path(@art), class: 'btn btn-primary'%> |
    <%= link_to 'Retour', arts_path, class: 'btn btn-primary'%>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Museevirtuel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">

  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark">
      <a href="./" class="navbar-brand" style="font-weight: 900; font-style: italic;">Musée - De la haine à la passion</a>
      <%= link_to 'Ajouter Œuvre',new_art_path, class: 'btn btn-primary'%>
    </nav>
    <div class="banierepage" style="position: relative; height:100vh; width:100vw;">
      <div class="grad">
        <div class="mestitres">
          <h1 class="titre1">Musée Virtuel</h1>
          <h2 class="titre2">De la haine à la passion</h2>
          <span class="blinking">➜</span>
        </div>
      </div>
    </div>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<link href='https://fonts.googleapis.com/css?family=Anton' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Neucha' rel='stylesheet' type='text/css'>
    
  <div class="container-fluid">
    <%= yield %>
  </div>

  </body>
</html>